# Generated by Django 3.1.7 on 2021-03-20 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('createQuestions', '0002_auto_20210320_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name_answer',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 9, 45, 34, 367485, tzinfo=utc)),
        ),
    ]
