# Generated by Django 3.1.7 on 2021-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createQuestions', '0003_auto_20210320_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
