# Generated by Django 3.1.7 on 2021-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Nam'), (0, 'Nữ')], default=0),
        ),
    ]
